trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  
stages:
- stage: 'Build'
  displayName: 'Build the Online Assessment application'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
      name: 'Azure Pipelines'
      demands:
      - npm

    variables:
      wwwrootDir: 'x' # Fill in
      dotnetSdkVersion: '6.x'
      psychBackendDir: 'modules/psychware/OnlineAssessment.Psychware.Backend'

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'
      
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '$(Build.SourcesDirectory)/$(psychBackendDir)/*.csproj' #'**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project'
      inputs:
        command: 'build'
        arguments: '--no-restore'
        projects: '$(Build.SourcesDirectory)/$(psychBackendDir)/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '$(Build.SourcesDirectory)/$(psychBackendDir)/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop